spring:
  application:
    name: eureka-server
server:
  port: 10000
eureka:
  instance:
    hostname: peer0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:10001/eureka/,http://peer2:10002/eureka/