spring:
  application:
    name: eureka-server
server:
  port: 10001
eureka:
  instance:
    hostname: peer1
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/,http://127.0.0.1:10002/eureka/