spring:
  application:
    name: eureka-server
server:
  port: 10001
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer0:10000/eureka/,http://peer2:10002/eureka/