spring:
  application:
    name: eureka-server
server:
  port: 10002
eureka:
  instance:
    hostname: peer2
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://peer1:10001/eureka/